import type { Metadata } from "next";
import { Inter , Baloo_Bhaijaan_2 } from "next/font/google";
import "./globals.css";

const inter = Baloo_Bhaijaan_2({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{backgroundColor:"black"}} className={inter.className}>{children}</body>
    </html>
  );
}
